export const FOUND_SESSION = 'FOUND_SESSION';
export const STOP_SESSION = 'STOP_SESSION';
export const NO_MATCH_FOUND = 'NO_MATCH_FOUND';
export const CHANGE_QUESTION_REQUEST = 'CHANGE_QUESTION_REQUEST';
