name: CI

on:
  pull_request:
      branches:
        - master
      paths:
        - 'backend/**'

defaults:
  run:
    working-directory: backend/functions

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: backend/functions/yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: backend/functions/yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build 
