name: Deploy backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend/functions

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-id: [cs3219-project-dev, cs3219-project-prod]
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache-dependency-path: backend/functions/yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Install Firebase
        run: yarn global add firebase-tools
      - name: Deploy functions
        run: |
          cd ../
          firebase -P ${{ matrix.project-id }} deploy -f --token ${{secrets.FIREBASE_CI_TOKEN}}
