name: deploy-service
on: [push]
jobs:
    deploy-backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Install libraries
              run: yarn install
            - name: Install Firebase
              run: yarn global add firebase-tools
            - name: Deploy functions
              run: firebase deploy --token ${{secrets.FIREBASE_CI_TOKEN}}
